import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
const contacts=fs.readFileSync(new URL('ui/contacts.js',root),'utf8');
const pending=[];
const nodes={contactsSearch:{value:'first',addEventListener(){}},contactsList:{dataset:{},innerHTML:''},contactsCount:{textContent:''}};
const context={document:{getElementById:id=>nodes[id]??null,addEventListener(){}},window:{},fetch:()=>new Promise(resolve=>pending.push(resolve)),setTimeout,clearTimeout,crypto:{randomUUID:()=> 'fixture-id'},confirm:()=>true};
vm.createContext(context);vm.runInContext(contacts,context);
const first=context.window.loadHomeServerContacts();nodes.contactsSearch.value='second';const second=context.window.loadHomeServerContacts();
pending[1]({ok:true,json:async()=>({items:[{id:2,display_name:'Second',authority_source:'homeserver'}]})});await second;
pending[0]({ok:true,json:async()=>({items:[{id:1,display_name:'First',authority_source:'homeserver'}]})});await first;
assert.equal(JSON.parse(nodes.contactsList.dataset.contacts)[0].id,2,'Late contact search replaced the latest results');
const tasks=fs.readFileSync(new URL('ui/tasks.js',root),'utf8');const loader=tasks.match(/const loadTasks = async \(\) => \{[^\n]+/)[0];
const taskPending=[],taskContext={state:{tasks:[],loadGeneration:0},$:()=>({value:'search'}),api:()=>new Promise(resolve=>taskPending.push(resolve)),renderTasks(){}};
vm.createContext(taskContext);vm.runInContext(loader+'\nglobalThis.load=loadTasks;',taskContext);
const a=taskContext.load(),b=taskContext.load();taskPending[1]({items:[{id:2}]});await b;taskPending[0]({items:[{id:1}]});await a;
assert.equal(taskContext.state.tasks[0].id,2,'Late task search replaced the latest results');
assert.match(contacts,/pendingCreate\.id/);assert.match(contacts,/expected_revision/);assert.match(tasks,/state\.createRequest\.id/);assert.match(tasks,/expected_revision/);
console.log('PRODUCTIVITY_UI_SECTION12=PASS');
