import assert from 'node:assert/strict';
import fs from 'node:fs';
const link=fs.readFileSync('app/services/tracky_visual_contact_link.py','utf8');
const physical=fs.readFileSync('app/services/tracky_physical_context.py','utf8');
const api=fs.readFileSync('app/onboarding_api.py','utf8');
const html=fs.readFileSync('ui/index.html','utf8');
assert.match(link,/def _next_cloud_revision/);
assert.match(link,/cloud_revision/);
assert.match(link,/cloud_last_accepted_revision/);
assert.match(link,/def prepare_cloud_snapshot/);
assert.match(link,/tracky\.visual\.cloud_sharing\.invalidated/);
assert.match(link,/def mark_cloud_delivery/);
assert.match(link,/revision: int \| None/);
assert.match(physical,/"visual_owner_status_revision": visual_owner_snapshot\["revision"\]/);
assert.match(physical,/"visual_owner_revision": visual_owner_snapshot\["revision"\]/);
assert.match(physical,/tracky_visual_contact_link\.prepare_cloud_snapshot\(\)/);
assert.match(physical,/body\.get\("visual_owner_status"\)/);
assert.match(physical,/cloud_receipt\.get\("accepted"\) is True/);
assert.match(physical,/cloud_receipt\["revision"\] == package\["visual_owner_revision"\]/);
assert.match(physical,/cloud_receipt\.get\("state"\) == package\["visual_owner_projection"\]/);
assert.match(api,/visual_status_current_generation_acknowledged/);
assert.match(html,/id="onboardVisualCloudConsent"/);
const payload=physical.slice(physical.indexOf('"payload": {'),physical.indexOf('"event_ids": event_ids'));
assert.doesNotMatch(payload,/("cloud_generation"|"visual_owner_generation"|"receipt_signature"|"participant_ref"|"contact_ref"|"embedding"|"portrait")/);
assert.doesNotMatch(link,/cloud_last_accepted_state.*\n.*authenticat.*site/);
console.log('TRACKY_VISUAL_ORDERED_SENDER_UI_V1F6: monotonic revision, explicit ordered ACK, no biometric export PASS');
