import assert from 'node:assert/strict';
import fs from 'node:fs';
const page=fs.readFileSync('ui/index.html','utf8');
const ui=fs.readFileSync('ui/tracky/agent-eyes.js','utf8');
const managed=fs.readFileSync('app/services/tracky_native_managed_session.py','utf8');
const wrapper=fs.readFileSync('app/services/tracky_agent_eyes.py','utf8');
const router=fs.readFileSync('app/onboarding_api.py','utf8');
const chat=fs.readFileSync('app/services/onboarding_chat.py','utf8');
const physical=fs.readFileSync('app/services/tracky_physical_context.py','utf8');
assert.match(page,/id="trackyAgentEyesPanel"/);
assert.match(page,/assets\/tracky\/agent-eyes.js/);
for(const name of ['Start','Stop','Consent','State','Camera','Samples','Details'])
  assert.match(page,new RegExp('id="trackyAgentEyes'+name+'"'));
assert.match(ui,/document\.visibilityState==='visible'/);
assert.match(ui,/armedHere/);
assert.match(ui,/if\(active&&armedHere\)/);
assert.match(ui,/scope:'owner-agent-eyes-supervised-live.v1'/);
assert.match(ui,/keepalive:true/);
assert.match(ui,/window\.confirm/);
assert.doesNotMatch(ui,/getUserMedia|VideoCapture|localStorage|sessionStorage/);
assert.match(wrapper,/managed\.start\(/);
assert.match(wrapper,/owner_surface=OWNER_SURFACE/);
assert.match(wrapper,/def agent_context\(/);
assert.match(wrapper,/manual_reapproval_required/);
assert.doesNotMatch(wrapper,/threading\.Thread|VideoCapture|cv2\.|raw_frame|base64/);
assert.match(managed,/requested_by=\("homeserver_owner_agent_eyes"/);
assert.match(managed,/owner_surface: str = "native_supervised"/);
assert.match(router,/@router\.post\("\/visual\/agent-eyes\/start"\)/);
assert.match(router,/return tracky_agent_eyes\.start\(\*\*payload\.model_dump\(\)\)/);
assert.match(chat,/"agent_eyes": tracky_agent_eyes\.agent_context\(\)/);
assert.match(physical,/"homeserver-owner-agent-eyes"/);
assert.match(physical,/"native_agent_eyes"/);
assert.match(physical,/"active_perception": bool\(provider\["remote_requestable"\]\)/);
console.log('TRACKY_AGENT_EYES_UI_V1G2: canonical worker, independent owner controls, visible tab lease, local-only PASS');
