import assert from 'node:assert/strict';
import fs from 'node:fs';
const html=fs.readFileSync('ui/index.html','utf8');
const js=fs.readFileSync('ui/tracky/agent-eyes.js','utf8');
const managed=fs.readFileSync('app/services/tracky_native_managed_session.py','utf8');
const evidence=fs.readFileSync('app/services/tracky_native_session_evidence.py','utf8');
const api=fs.readFileSync('app/onboarding_api.py','utf8');
assert.match(html,/id="trackyAgentEyesInterval"/);
assert.match(html,/data-extended="true"/);
assert.match(html,/id="trackyAgentEyesExtendedStatus"/);
assert.match(js,/extendedEligible/);
assert.match(js,/interval_seconds:interval/);
assert.match(js,/!extendedEligible/);
assert.match(managed,/AGENT_EXTENDED_WALL_OPTIONS = \(300, 600\)/);
assert.match(managed,/AGENT_EXTENDED_MAX_SAMPLES = 60/);
assert.match(managed,/acceptance\.status\(\)\["owner_exercise_complete"\]/);
assert.match(evidence,/60 if row\.get\("owner_surface"\) == "agent_eyes" else 12/);
assert.match(api,/max_session_seconds: int = Field\(default=120, strict=True, ge=60, le=600\)/);
assert.doesNotMatch(js,/getUserMedia|VideoCapture|sessionStorage|localStorage/);
console.log('TRACKY_AGENT_EYES_EXTENDED_UI_V1G2B4: reviewed owner-only budgets, no new camera runtime PASS');
