import assert from 'node:assert/strict';
import fs from 'node:fs';
const js=fs.readFileSync('ui/tracky/native-camera.js','utf8');
const api=fs.readFileSync('app/onboarding_api.py','utf8');
const diagnosis=fs.readFileSync('app/services/tracky_native_diagnosis.py','utf8');
const repair=fs.readFileSync('app/services/health_repair.py','utf8');
const runtime=fs.readFileSync('app/services/tracky_native_camera.py','utf8');
assert.match(js,/call\('diagnose'\)/);
assert.match(js,/current\.last_test_status/,'live diagnostic state must survive a page reload');
assert.match(js,/call\('privacy-review'/,'separate read-only privacy challenge');
assert.match(js,/window\.confirm\(/);
assert.match(js,/onboardNativeConsent/);
assert.doesNotMatch(js,/getUserMedia|setInterval\(\s*.*test\(/);
assert.match(api,/visual\/native\/diagnose/);
assert.match(api,/visual\/native\/privacy-review/);
assert.match(api,/_require_ui\(x_requested_with\)/);
assert.match(diagnosis,/def _model_preflight\(/);
assert.match(diagnosis,/def before_test\(/);
assert.match(diagnosis,/def after_test\(/);
assert.match(diagnosis,/hardware_certified": False/);
assert.match(diagnosis,/automated": False/);
assert.match(repair,/def _native_tracky_issues\(/);
assert.match(repair,/owner_approval_required=True/);
assert.match(runtime,/camera_release_completed": True/);
assert.match(runtime,/capture_and_inference_ms/);
assert.match(runtime,/driver_worker_exited/);
assert.doesNotMatch(diagnosis,/pip install|subprocess.run/);
console.log('TRACKY_NATIVE_DIAGNOSIS_UI_V1C: Agent Chat preflight, explicit consent, recovery, safe repair PASS');
