import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8');
const source=read('ui/tracky/native-camera.js');
const html=read('ui/index.html');
const backend=read('app/services/tracky_native_camera.py');
const api=read('app/onboarding_api.py');
const spec=read('HomeServer.spec');
assert.match(html,/id="onboardNativeCamera"/);
assert.match(html,/id="onboardNativeConsent"/);
assert.match(html,/id="onboardNativeIndex"/);
assert.match(html,/tracky\/native-camera.js/);
assert.match(source,/if\(!\(\$\('onboardNativeConsent'\)\?\.checked\)\)/);
assert.match(source,/window\.confirm/);
assert.match(source,/camera_index:index/);
assert.match(source,/homeserver:onboarding-hidden/);
assert.match(source,/pagehide/);
assert.match(source,/api\/v1\/control\/onboarding\/visual\/native/);
assert.doesNotMatch(source,/getUserMedia|toDataURL|frameData|embedding/);
assert.match(backend,/cv2\.VideoCapture\(index\)/);
assert.match(backend,/cv2\.CascadeClassifier/);
assert.match(backend,/capture\.release\(\)/);
assert.match(backend,/tracky\.active_perception\(/);
assert.match(backend,/replace=False/);
assert.match(backend,/unregister_provider\(expected=_provider\)/);
assert.match(backend,/identity_recognition": False/);
assert.match(api,/class NativeCameraTest\(BaseModel\)/);
assert.match(api,/camera_index: int = Field\(strict=True/);
assert.match(spec,/collect_all\('cv2'\)/);
assert.match(read('requirements.txt'),/opencv-python-headless==4\.10\.0\.84/);
console.log('Native Tracky Agent Chat, build, privacy and bounded API contracts: PASS');
