import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('ui/tracky/agent-eyes-scene.js','utf8');
const nodes={};for(const id of ['Panel','Model','Room','Enabled','Observed','Configure','Accept','Disable','Refresh','Status','Preview'])nodes['trackyScene'+id]={value:'studio',checked:false,textContent:'',disabled:false,children:[],replaceChildren(){this.children=[];},append(v){this.children.push(v);},addEventListener(e,fn){this[e]=fn;}};
let visible=true,resolvePending,handler,interval,now=0;
const requests=[],timers=[];
const document={readyState:'complete',visibilityState:'visible',getElementById:id=>id==='view-tracky'?{classList:{contains:()=>visible}}:nodes[id],createElement:()=>({}),addEventListener(){}};
const state={configured:true,reviewed:false,test_completed:true,rooms:[{room_id:'studio',name:'<img src=x>'}],preview:{objects:['chair'],setting:'indoor',lighting:'dim',age_seconds:59}};
const sandbox={document,window:{confirm:()=>true},Date:{now:()=>now},setInterval:fn=>{interval=fn;},setTimeout:(fn,ms)=>{timers.push({fn,ms});return timers.length;},clearTimeout(){},fetch:async(path,options)=>{requests.push({path,options});if(handler)return handler();return {ok:true,json:async()=>state};}};
vm.runInNewContext(source,sandbox);
const flush=()=>new Promise(r=>setImmediate(r));await flush();
assert.match(nodes.trackyScenePreview.textContent,/chair/);
assert.equal(timers.at(-1).ms,1000);timers.at(-1).fn();assert.doesNotMatch(nodes.trackyScenePreview.textContent,/chair/);
assert.equal(nodes.trackySceneRoom.children[0].textContent,'<img src=x>');
assert.equal(JSON.stringify(sandbox.window.TrackyAgentEyesScene.options()),'{}');
nodes.trackySceneEnabled.checked=true;assert.equal(sandbox.window.TrackyAgentEyesScene.options().scene_test,true);
state.reviewed=true;await interval();await flush();assert.equal(sandbox.window.TrackyAgentEyesScene.options().scene_test,false);
handler=()=>new Promise(r=>{resolvePending=r;});nodes.trackySceneRefresh.click();await flush();assert.equal(nodes.trackyScenePreview.textContent,'');now+=2000;
resolvePending({ok:true,json:async()=>state});await flush();assert.doesNotMatch(nodes.trackyScenePreview.textContent,/chair/);
handler=null;visible=false;const count=requests.length;nodes.trackySceneConfigure.click();await flush();assert.equal(requests.length,count);
visible=true;handler=async()=>{throw Error('offline');};await interval();await flush();assert.equal(nodes.trackyScenePreview.textContent,'');assert.equal(sandbox.window.TrackyAgentEyesScene.options().scene_test,true);
assert.ok(requests.every(r=>r.options.cache==='no-store'));
assert.doesNotMatch(source,/innerHTML|getUserMedia|localStorage|sessionStorage/);
console.log('TRACKY_AGENT_EYES_SCENE_UI_V1G3C: off default, model review, native session options, expiry/transit, safe text, visibility PASS');
