/* One-shot HomeServer Tracky camera/inference UI contract. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
const ui=fs.readFileSync('ui/tracky/eyes-runtime.js','utf8');
const html=fs.readFileSync('ui/index.html','utf8');
const original=fs.readFileSync('ui/tracky/owner-visual.js','utf8');
const api=fs.readFileSync('app/onboarding_api.py','utf8');
const backend=fs.readFileSync('app/services/tracky_owner_perception.py','utf8');
assert.match(html,/id="onboardEyesConsent"/);
assert.match(html,/id="onboardEyesStart"/);
assert.match(html,/id="onboardEyesStop"/);
assert.match(html,/No image, face descriptor/);
assert.match(ui,/if\(!consent\?\.checked\)/);
assert.match(ui,/window\.confirm\(/);
assert.match(ui,/navigator\.mediaDevices\.getUserMedia\(\{/);
assert.match(ui,/description:\{enabled:false\}/,'one-shot test disables biometric description');
assert.match(ui,/await engine\.detect\(video\)/,'real browser model observation occurs');
assert.match(ui,/face_count:Math\.min\(2,faces\.length\)/,'only bounded counts are sent');
assert.match(ui,/session,request_id:pending\.request_id/);
assert.match(ui,/api\('heartbeat'/);
assert.match(ui,/api\('close'/);
assert.match(ui,/visibilitychange/);
assert.match(ui,/homeserver:onboarding-hidden/);
assert.match(original,/TrackyOwnerEyes\?\.isActive\(\)/,'cannot open concurrent enrollment camera');
assert.doesNotMatch(ui,/face\.embedding|frameData|dataURL|toDataURL/);
assert.match(api,/class EyesObservation\(EyesSession\)/);
assert.match(api,/model_config = ConfigDict\(extra="forbid"\)/);
assert.match(backend,/requested_by.*ALLOWED_CALLER/);
assert.match(backend,/request_id.*_ALLOWED_REQUEST/);
assert.match(backend,/provider_certified": False/);
assert.match(backend,/server_native_camera_certified": False/);
console.log('TRACKY_OWNER_PERCEPTION_UI: owner gesture, model, no biometrics, revocation and guarded provider PASS');
