from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

KEY_RE=re.compile(r"^[a-z0-9][a-z0-9._-]{1,79}$")

INDEX_HTML="""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{APP_NAME}}</title>
<link rel="stylesheet" href="assets/app.css">
</head>
<body>
<main class="vp3-app-shell">
  <header><span class="vp3-kicker">VP3 HomeServer App</span><h1>{{APP_NAME}}</h1></header>
  <section class="vp3-card">
    <h2>Ready to build.</h2>
    <p>This app was created from the VP3 HomeServer App SDK.</p>
  </section>
</main>
<script src="assets/vp3-sdk.js"></script>
<script src="assets/app.js"></script>
</body>
</html>
"""

APP_CSS="""*{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f5f6f8;color:#15171a}.vp3-app-shell{max-width:1100px;margin:0 auto;padding:32px}.vp3-kicker{font-size:12px;text-transform:uppercase;letter-spacing:.12em;color:#667085}.vp3-card{background:#fff;border:1px solid #e4e7ec;border-radius:16px;padding:24px;box-shadow:0 8px 30px rgba(16,24,40,.05)}"""

SDK_JS="""window.VP3App={
version:"1.2",
health:()=>({ok:true,sdk:"1.2"}),
ready(cb){if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",cb,{once:true});}else{cb();}},
base(){const parts=location.pathname.split("/");const i=parts.indexOf("homeserver-apps");return i>=0?parts.slice(0,i+2).join("/"):"";},
async emit(topic,payload={}){const r=await fetch(this.base()+"/runtime/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({topic,payload})});if(!r.ok)throw new Error(await r.text());return r.json();},
async events(){const r=await fetch(this.base()+"/runtime/events");if(!r.ok)throw new Error(await r.text());return r.json();},
async runJob(jobId){const r=await fetch(this.base()+"/runtime/jobs/"+encodeURIComponent(jobId)+"/run",{method:"POST"});if(!r.ok)throw new Error(await r.text());return r.json();},
async writeFile(path,blob){const f=new FormData();f.append("file",blob instanceof Blob?blob:new Blob([blob]));const r=await fetch(this.base()+"/data/file?path="+encodeURIComponent(path),{method:"PUT",body:f});if(!r.ok)throw new Error(await r.text());return r.json();},
async readFile(path){const r=await fetch(this.base()+"/data/file?path="+encodeURIComponent(path));if(!r.ok)throw new Error(await r.text());return r.arrayBuffer();},
async deleteFile(path){const r=await fetch(this.base()+"/data/file?path="+encodeURIComponent(path),{method:"DELETE"});if(!r.ok)throw new Error(await r.text());return r.json();},
async permissions(){const r=await fetch(this.base()+"/permissions");if(!r.ok)throw new Error(await r.text());return r.json();},
async resources(){const r=await fetch(this.base()+"/resources");if(!r.ok)throw new Error(await r.text());return r.json();},
async runtime(){const r=await fetch(this.base()+"/runtime/services");if(!r.ok)throw new Error(await r.text());return r.json();}
};"""

APP_JS="""VP3App.ready(()=>{console.log("VP3 app ready",VP3App.health());});"""

SETTINGS="""{
  "contract":"vp3.app.settings-schema.v1",
  "fields":[]
}
"""

ACTIONS="""{
  "contract":"vp3.app.agent-actions.v2",
  "actions":[]
}
"""

README="""# {{APP_NAME}}

Generated by the VP3 HomeServer App SDK.

## Included
- VP3 app manifest
- responsive VP3 shell
- SDK bootstrap
- settings schema
- Agent action schema
- SQLite migrations directory
- health metadata
- package-ready structure
- runtime jobs and event contracts

Build app-specific features inside this scaffold instead of recreating HomeServer integration from scratch.
"""

def create(root:Path,key:str,name:str,runtime:str,permissions:list[str]|None=None)->Path:
    key=key.strip().lower()
    name=name.strip()
    if not KEY_RE.fullmatch(key):
        raise SystemExit("Invalid app key.")
    if not name:
        raise SystemExit("App name is required.")
    target=(root/key).resolve()
    root=root.resolve()
    if root not in target.parents:
        raise SystemExit("Unsafe target path.")
    if target.exists():
        raise SystemExit("Target app already exists.")
    (target/"assets").mkdir(parents=True)
    (target/"database"/"migrations").mkdir(parents=True)
    (target/"agent").mkdir(parents=True)
    (target/"runtime").mkdir(parents=True)
    (target/"sample").mkdir(parents=True)
    manifest={
        "contract":"vp3.app.package.v1",
        "app_key":key,
        "name":name,
        "version":"0.1.0",
        "runtime":runtime,
        "entrypoint":"index.html" if runtime=="static" else "index.php",
        "sdk_version":"1.2",
        "permissions":sorted(set(permissions or [])),
        "settings_schema":"settings.schema.json",
        "database_migrations":"database/migrations",
        "agent_actions":"agent/actions.json",
        "jobs":"runtime/jobs.json",
        "events":"runtime/events.json",
        "sample_data":"sample/data.json",
        "release_channel":"stable",
        "release_notes":["Initial VP3 HomeServer App SDK release."],
        "data_schema_version":"1",
        "data_migration_reversible":True,
        "routes":{"local":True,"private_remote":False,"public":False},
    }
    (target/"vp3-app.json").write_text(json.dumps(manifest,indent=2)+"\n",encoding="utf-8")
    page=INDEX_HTML.replace("{{APP_NAME}}",name)
    if runtime=="static":
        (target/"index.html").write_text(page,encoding="utf-8")
    else:
        (target/"index.php").write_text("<?php declare(strict_types=1); ?>\n"+page,encoding="utf-8")
    (target/"assets"/"vp3-sdk.js").write_text(SDK_JS+"\n",encoding="utf-8")
    (target/"assets"/"app.css").write_text(APP_CSS+"\n",encoding="utf-8")
    (target/"assets"/"app.js").write_text(APP_JS+"\n",encoding="utf-8")
    (target/"settings.schema.json").write_text(SETTINGS+"\n",encoding="utf-8")
    (target/"agent"/"actions.json").write_text(ACTIONS+"\n",encoding="utf-8")
    (target/"runtime"/"jobs.json").write_text(json.dumps({"contract":"vp3.app.jobs.v1","jobs":[]},indent=2)+"\n",encoding="utf-8")
    (target/"runtime"/"events.json").write_text(json.dumps({"contract":"vp3.app.events.v1","subscriptions":[]},indent=2)+"\n",encoding="utf-8")
    (target/"sample"/"data.json").write_text(json.dumps({"contract":"vp3.app.sample-data.v1","items":[{"id":"welcome","title":"Sample item","description":"Replace this with app-specific demo data."}]},indent=2)+"\n",encoding="utf-8")
    (target/"database"/"migrations"/"README.md").write_text("# Data schema changes\n\nHomeServer snapshots app data before data_schema_version changes. User-app schema execution is app-managed; package SQL is never executed automatically.\n",encoding="utf-8")
    (target/"README.md").write_text(README.replace("{{APP_NAME}}",name),encoding="utf-8")
    return target

def main()->None:
    parser=argparse.ArgumentParser(description="Create a VP3 HomeServer user app from the canonical SDK.")
    parser.add_argument("app_key")
    parser.add_argument("name")
    parser.add_argument("--runtime",choices=("static","php"),default="static")
    parser.add_argument("--output",default=".")
    parser.add_argument("--permission",action="append",default=[],help="Declare a HomeServer permission; repeat as needed.")
    args=parser.parse_args()
    print(create(Path(args.output),args.app_key,args.name,args.runtime,args.permission))

if __name__=="__main__":
    main()
